name: studify
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  flutter_bloc: ^8.1.6
  bloc: ^8.1.4
  animated_notch_bottom_bar: ^1.0.3
  go_router: ^13.0.0
  flutter_screenutil: ^5.6.0
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  equatable: ^2.0.5
  provider: ^6.1.2
  enefty_icons: ^1.0.7
  shimmer: ^3.0.0

dev_dependencies:
  launcher_name: ^1.0.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
launcher_name:
  default: "Studify"
flutter:
  uses-material-design: true

  fonts:
    - family: Jost
      fonts:
        - asset: assets/fonts/Jost-Regular.ttf
        - asset: assets/fonts/Jost-Bold.ttf
          weight: 700
        - asset: assets/fonts/Jost-Italic.ttf
          style: italic
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish-Regular.ttf
        - asset: assets/fonts/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mulish-Italic.ttf
          style: italic
  assets:
    - assets/images/default_avatar.png
    - assets/images/all_logo.png
    - assets/images/homebg.png
